### ISSUE TITLE
The logfile_dir does not work (Typo3 v7.3)

### ISSUE THREAD

**Issue by al-Iskandar** [netcoop/t3ext-retrostats#1] opened 2015-06-22 20:17 UTC
I created an AdditionalConfiguration.php in typo3conf:

Variation 1 (according your readme):

<?php
    $TYPO3_CONF_VARS['FE']['logfile_dir'] = 'logfiles/';
?>

Variation 2 (according other manuals):

<?php
    $GLOBALS['TYPO3_CONV_VARS']['FE']['logfile_dir'] = 'logfiles/';
?>

I tried it also with a sub directory of fileadmin.

But the logfiles are always written into the base directory of the Typo3 installation. The manual is a little bit Laconic...

**Comment by netcoop** [comment] 2015-06-23 12:25
The second version should work. Did you clear all the caches (via Install Tool?).
You're welcome to contribute to the manual.

**Comment by al-Iskandar** [comment] 2015-06-23 18:12
I tried it again, cleared all caches incl. opcache - but without success

**Comment by x4e-salvi** [comment] 2016-05-10 16:01
There's a typo:
wrong: $GLOBALS['TYPO3_CONV_VARS']['FE']['logfile_dir'] = 'logfiles/';
correct: $GLOBALS['TYPO3_CONF_VARS']['FE']['logfile_dir'] = 'logfiles/';

This should be fixed in the retrostats manual, section configuration: 
"The ['TYPO3_CONV_VARS']['FE']['logfile_dir'] setting should be placed in AdditionalConfiguration.php instead of LocalConfiguration.php, because the Install tool will remove it as it's no longer a known TYPO3 setting."

**Comment by netcoop** [comment] 2016-05-10 20:47
Thanks! I didn't notice that silly typo, and it looks like it's the cause of this issue. I'll push an updated readme.

**Closed as completed** 2016-05-10 20:54 UTC
